#### Uključivanje potrebnih biblioteka
- Biblioteka pandas - omogućava nam rad sad dataset-om (mogućnost čitanja, pisanja, modifikacije i sl.)
- Biblioteka numpy - omogućava nam rad sa matematičkim funkcijama, nizovima, listama i sl.

In [2]:
import pandas as pd
import numpy as np

# Uključivanje dataset-a i njegov opis
- Link: https://www.kaggle.com/datasets/fedesoriano/air-quality-data-set?resource=download&select=AirQuality.csv
- Opis: 
    - Dataset sadrži podatke dobijene od senzora zagadjenosti vazduha postavljenog u Italijanskom gradu od 2004. do 2005. godine
    - Kolone:
        - Datum (DD/MM/YYYY)
        - Vreme (HH.MM.SS)
        - Tačna jednočasovna prosečna koncentracija CO u mg/m³
        - PT08.S1 (kalaj-oksid) – prosečan jednočasovni odziv senzora (nominalno cilja CO)
        - Tačna jednočasovna prosečna koncentracija nemetanskih ugljovodonika u µg/m³ (referentni analizator)
        - Tačna jednočasovna prosečna koncentracija benzena u µg/m³ (referentni analizator)
        - PT08.S2 (titanijum-dioksid) – prosečan jednočasovni odziv senzora (nominalno cilja NMHC)
        - Tačna jednočasovna prosečna koncentracija NOx u ppb (referentni analizator)
        - PT08.S3 (volfram-oksid) – prosečan jednočasovni odziv senzora (nominalno cilja NOx)
        - Tačna jednočasovna prosečna koncentracija NO₂ u µg/m³ (referentni analizator)
        - PT08.S4 (volfram-oksid) – prosečan jednočasovni odziv senzora (nominalno cilja NO₂)
        - PT08.S5 (indijum-oksid) – prosečan jednočasovni odziv senzora (nominalno cilja O₃)
        - Temperatura u °C
        - Relativna vlažnost vazduha (%)
        - AH – apsolutna vlažnost

- Skup podataka sadrži 9357 instanci sa satnim prosečnim vrednostima odziva niza od 5 metal-oksidnih hemijskih senzora ugrađenih u uređaj za merenje kvaliteta vazduha. Uređaj je bio postavljen na terenu u značajno zagađenom području, na nivou puta, u jednom italijanskom gradu. Podaci su prikupljani od marta 2004. do februara 2005. godine (jedna godina), što predstavlja najduže slobodno dostupno snimanje odziva senzora za kvalitet vazduha postavljenih na terenu.
- Referentne satne prosečne koncentracije za CO, nemetanske ugljovodonike, benzen, ukupne azotne okside (NOx) i azot-dioksid (NO₂) obezbeđene su od strane sertifikovanog analizatora koji je bio postavljen zajedno sa uređajem. U podacima postoje dokazi o unakrsnoj osetljivosti, kao i o „concept drift“ i „sensor drift“ pojavama, što je opisano u radu De Vito i saradnici, Sens. And Act. B, Vol. 129,2,2008 (navod je obavezan), a što eventualno utiče na sposobnosti senzora da precizno procene koncentracije.
- Nedostajuće vrednosti su označene sa vrednošću -200.
- Ovaj skup podataka može se koristiti isključivo u istraživačke svrhe. Komercijalna upotreba je potpuno isključena.

In [ ]:
df = pd.read_csv('AirQuality.csv', sep=';') # koristimo sep=';' jer su kolone odvojene sa tačka-zarezom

Koristeći funkciju .head(int n) možemo dobiti prvih n redova za dataset-a sa nazivima kolona, kako bi mogli da vidimo primer šta se nalazi u istom.

In [6]:
df.head(10)

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN
5,10/03/2004,23.00.00,"1,2",1197.0,38.0,"4,7",750.0,89.0,1337.0,96.0,1393.0,949.0,"11,2","59,2","0,7848",NaN,NaN
6,11/03/2004,00.00.00,"1,2",1185.0,31.0,"3,6",690.0,62.0,1462.0,77.0,1333.0,733.0,"11,3","56,8","0,7603",NaN,NaN
7,11/03/2004,01.00.00,1,1136.0,31.0,"3,3",672.0,62.0,1453.0,76.0,1333.0,730.0,"10,7","60,0","0,7702",NaN,NaN
8,11/03/2004,02.00.00,"0,9",1094.0,24.0,"2,3",609.0,45.0,1579.0,60.0,1276.0,620.0,"10,7","59,7","0,7648",NaN,NaN
9,11/03/2004,03.00.00,"0,6",1010.0,19.0,"1,7",561.0,-200.0,1705.0,-200.0,1235.0,501.0,"10,3","60,2","0,7517",NaN,NaN

Koristeći funkciju .shape, možemo dobiti dimenzije našeg dataset-a (u našem slučaju se one nalaze ispod 9471 red i 17 kolona)

In [7]:
df.shape

(9471, 17)

Koristeći .describe() funkciju možemo da dobijemo neke osnovne statističke podatke vezane za naš dataset

In [8]:
df.describe()

,PT08.S1(CO),NMHC(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),Unnamed: 15,Unnamed: 16
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,0.0,0.0
mean,1048.990061,-159.090093,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,NaN,NaN
std,329.832710,139.789093,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,NaN,NaN
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,NaN,NaN
25%,921.000000,-200.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,NaN,NaN
50%,1053.000000,-200.000000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,NaN,NaN
75%,1221.000000,-200.000000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,NaN,NaN
max,2040.000000,1189.000000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,NaN,NaN

Koristeći funkciju .info(), možemo dobiti podatke o tipovima kolona, da li je broj ili objekat (sve ostalo)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   object
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   object
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   object
 13  RH             9357 non-null   object
 14  AH             9357 non-null   object
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(10), object(7)
memory usage: 1.2+ MB